spring.application.name=ems-backend

server.port=${PORT:8080}

spring.datasource.url=${AIVEN_MYSQL_URI}
spring.datasource.username=${AIVEN_USER}
spring.datasource.password=${AIVEN_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 #auto detects driver



# Hibernate maps Java objects to database tables
# Hibernate uses the dialect specification to create SQL statements
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# tells Hibernate to auto-create table if it doesn't exist
# & to update if it does exist and some changes were made
spring.jpa.hibernate.ddl-auto=update
